spring:
  application:
    name: CUSTOMER-SERVICE
  mongodb:
    username: soumya
    password: tiger
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin


server:
  port: 8090