spring:
  application:
    name: CUSTOMER-SERVICE
  mongodb:
    username: soumya
    password: tiger
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin

eureka:
  instance:
    prefer-ip-address: true

server:
  port: 8090