server:
  port: 8999

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
            -
        - id: order-line-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-line/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
