spring:
  application:
    name: NOTIFICATION-SERVICE
  mongodb:
    username: soumya
    password: tiger
    host: localhost
    port: 27017
    database: notification
    authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # use * for local development or unsecure networks
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: |
          orderConfirmation:com.ecommerce.common.events.OrderConfirmationEvent,
          paymentConfirmation:com.ecommerce.common.events.PaymentNotificationRequestEvent

  mail:
    host: localhost
    port: 1025
    username: soumya
    password: tiger
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  sender-email: ${SENDER_MAIL}

eureka:
  instance:
    prefer-ip-address: true

server:
  port: 8066
