spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: soumya
    password: tiger
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  servlet:
    context-path: /api/v1
  port: 8060

application:
  config:
    customer-url: http://localhost:8090/api/v1/customer
    product-url: http://localhost:8050/api/v1/product
    payment-url: http://localhsot:8070/api/v1/payment